"""
Digital Freedom Quest - An inspiring story for young traders.

This narrative follows a young trader's journey from zero to financial independence,
blending trading wisdom with motivational storytelling for Gen Z and young millennials.
"""

import random
from stories.story_engine import BaseStory


class DigitalFreedomQuest(BaseStory):
    """
    Epic narrative: The Rise of the Digital Trader.

    A story about a young trader's journey to financial independence,
    featuring real trading wisdom, market insights, and personal growth.
    """

    def __init__(self):
        """Initialize the Digital Freedom Quest story."""
        super().__init__(
            story_id="digital_freedom_quest",
            title="🚀 Digital Freedom Quest",
            description=(
                "The epic journey of a young trader who decided to take control of their future. "
                "Follow Alex as they navigate market volatility, learn from failures, and build "
                "a path to financial independence. A story for anyone tired of waiting for "
                "someone else to build their dreams."
            ),
            target_audience="Youth (Gen Z & Young Millennials, 18-35)"
        )

    def _setup_chapters(self) -> None:
        """Setup all story chapters for Digital Freedom Quest."""
        # Create chapters - will generate 5-10 chapters randomly
        base_chapters = {
            0: {
                "title": "The Awakening",
                "emoji": "⚡",
                "content": (
                    "Alex was 24. Living paycheck to paycheck. Watching influencers on TikTok "
                    "talk about wealth while their own bank account screamed poverty.\n\n"
                    "One night at 2 AM, scrolling through Reddit, Alex discovered something: "
                    "Alpaca Markets. Free API. Instant trades. No minimum. No gatekeepers.\n\n"
                    "That's when it hit them. Nobody was coming to save them. No lottery. "
                    "No inheritance. Just data, discipline, and 24 hours in a day.\n\n"
                    "They opened a notebook and wrote: 'I will build my own future.'\n\n"
                    "This wasn't luck. This was momentum."
                )
            },
            1: {
                "title": "The First 1000 Dollars",
                "emoji": "💰",
                "content": (
                    "The first investment felt terrifying. $1,000 - three months of saved coffee money, "
                    "skipped dinners, and overtime shifts.\n\n"
                    "Alex set up the trading bot. Watched the dashboard light up with green and red "
                    "candles. Momentum indicators flickering. Win rate climbing.\n\n"
                    "Three weeks later: +$247 profit.\n\n"
                    "Not much? Maybe. But it was THEIRS. Not a salary someone could take away. "
                    "Not a job someone could fire them from. Pure alpha generated by their own "
                    "algorithmic thinking.\n\n"
                    "Alex smiled for the first time that month.\n\n"
                    "'This is just the beginning,' they whispered to the screen."
                )
            },
            2: {
                "title": "The Crash",
                "emoji": "📉",
                "content": (
                    "Month three brought a market correction. -$340 in two days.\n\n"
                    "Alex's stomach twisted. All that progress, gone. They checked the bot's logs "
                    "obsessively. Searched for what went wrong. Watched YouTube videos at 3 AM "
                    "about 'stop losses' and 'risk management.'\n\n"
                    "That's when the real education started.\n\n"
                    "Not the kind you pay for. The kind that costs money to learn.\n\n"
                    "Alex realized: volatility wasn't an enemy. It was a teacher. Every loss was "
                    "tuition in the market's school. And they were finally starting to pass.\n\n"
                    "They refactored their strategy. Added better momentum calculations. Tighter "
                    "risk controls. And waited.\n\n"
                    "'The crash taught me more than years of academic finance,' Alex noted in "
                    "their trading journal."
                )
            },
            3: {
                "title": "The Momentum Discovered",
                "emoji": "📈",
                "content": (
                    "It was a Tuesday when Alex cracked the code.\n\n"
                    "Studying 1-year momentum patterns, something clicked. The algorithm that "
                    "seemed random suddenly made sense. Stocks with true momentum don't just "
                    "rise randomly. They follow patterns. Psychological patterns. Market patterns.\n\n"
                    "Alex optimized for TOP 50 momentum leaders. Equal weight portfolio. "
                    "Rebalance every 22 trading days.\n\n"
                    "That month: +$1,890. Their portfolio doubled.\n\n"
                    "Now they had $2,247. Not rich by traditional standards. But for the first time, "
                    "they saw a clear path. If this growth continued...\n\n"
                    "'If momentum works, and I keep learning, nothing can stop me.' Alex realized "
                    "they were no longer just trading. They were building a system."
                )
            },
            4: {
                "title": "The System Takes Shape",
                "emoji": "⚙️",
                "content": (
                    "Six months in, Alex had built something beautiful.\n\n"
                    "Not just a trading bot. A SYSTEM:\n"
                    "• Automated rebalancing (zero emotion)\n"
                    "• Momentum-based stock selection (proven strategy)\n"
                    "• Risk management with position limits\n"
                    "• Telegram notifications for real-time monitoring\n\n"
                    "Their portfolio grew from $1,000 to $4,500. Not life-changing yet. "
                    "But the trajectory was clear.\n\n"
                    "More importantly, Alex had built KNOWLEDGE:\n"
                    "✓ Market mechanics\n"
                    "✓ Algorithm design\n"
                    "✓ Risk management\n"
                    "✓ Discipline under pressure\n\n"
                    "'I'm not just a trader anymore,' Alex thought. 'I'm an engineer of my own fortune.'"
                )
            },
            5: {
                "title": "The First Investor",
                "emoji": "🤝",
                "content": (
                    "Month nine. Alex's college friend Sarah saw their results.\n\n"
                    "'How are you doing this?' she asked.\n\n"
                    "For the first time, Alex shared the system. Not the code (that was proprietary), "
                    "but the IDEA. The philosophy. The discipline.\n\n"
                    "Sarah was amazed. 'Can you manage money for me?'\n\n"
                    "That's when Alex realized: they weren't just solving their own financial problem. "
                    "They were building something that could help others.\n\n"
                    "They set up a separate investor account. Three allocations:\n"
                    "• Low-risk (conservative)\n"
                    "• Medium-risk (balanced)\n"
                    "• High-risk (aggressive)\n\n"
                    "Sarah's $5,000 went to medium allocation. Within two months: +$1,200.\n\n"
                    "'Alex, I'm in. I'm trusting you with my future.' Sarah messaged.\n\n"
                    "Alex felt the weight of responsibility. And loved it."
                )
            },
            6: {
                "title": "The Inflection Point",
                "emoji": "🎯",
                "content": (
                    "One year in. Alex's portfolio: $12,400. Sarah's: $8,900. Two other friends "
                    "joined. Total AUM: $31,200.\n\n"
                    "By some measures, still small. But Alex had achieved something rare:\n\n"
                    "PROOF OF CONCEPT.\n\n"
                    "Their system worked consistently across different market conditions. "
                    "Different risk profiles. Different investors.\n\n"
                    "At their day job, Alex made $45,000/year. Their trading was now generating "
                    "that same income. Passive. Automated. Scalable.\n\n"
                    "The math was clear: keep the bot running while starting to build a proper "
                    "wealth management business.\n\n"
                    "'I've proven it works on paper,' Alex told their mentor. 'Now I'm going to "
                    "prove it at scale.'"
                )
            },
            7: {
                "title": "The Scaling Decision",
                "emoji": "📊",
                "content": (
                    "Year 18 months. Alex faced a choice: Stay comfortable or climb higher.\n\n"
                    "They quit their day job. Registered as a registered investment advisor. "
                    "Created proper investor agreements. Built compliance systems.\n\n"
                    "Within 6 months: 23 investors. $180,000 AUM.\n\n"
                    "The portfolio was now running across multiple strategies:\n"
                    "• Paper Low (conservative S&P 500)\n"
                    "• Paper Medium (S&P 500 + growth stocks)\n"
                    "• Paper High (aggressive momentum plays)\n\n"
                    "Each strategy had its own bot. Different API keys. Different ticker universes. "
                    "All feeding into a unified Telegram dashboard.\n\n"
                    "On a Tuesday, Alex watched all three bots rebalance simultaneously. "
                    "Green checksmarks. Perfect execution.\n\n"
                    "'This is what freedom feels like,' Alex whispered, watching the Telegram logs.\n\n"
                    "No manager. No politics. Just pure algorithmic performance."
                )
            },
            8: {
                "title": "The Generational Impact",
                "emoji": "🌟",
                "content": (
                    "Two years later. Alex's investors had grown their wealth 34% annually on average. "
                    "One investor, Marcus (a nurse), was able to cut his shifts in half. "
                    "His family stress dropped. He was present for his kids.\n\n"
                    "Sarah, the first investor, had enough passive income to take a 6-month sabbatical "
                    "to travel Europe. Something she thought was impossible.\n\n"
                    "These weren't lottery winners. They were people who trusted Alex's system.\n\n"
                    "Alex's portfolio had grown to $380,000 personally. Not ultra-wealthy by billionaire "
                    "standards. But completely, utterly financially independent.\n\n"
                    "They could:\n"
                    "✓ Work only on projects they loved\n"
                    "✓ Take months off whenever they wanted\n"
                    "✓ Sleep without financial anxiety\n"
                    "✓ Help family members\n"
                    "✓ Invest in passion projects\n\n"
                    "\"I'm not just rich,\" Alex realized. \"I'm free.\""
                )
            },
            9: {
                "title": "The Message to Younger Alex",
                "emoji": "💌",
                "content": (
                    "Three years after that 2 AM Reddit scroll, Alex recorded a message for their "
                    "Discord community of young traders:\n\n"
                    "'If you're reading this at midnight on your phone with $200 to your name, "
                    "wondering if it's possible... YES.\n\n"
                    "Not because trading is magic. It's not.\n\n"
                    "It's possible because:\n"
                    "1. Technology broke gatekeepers (Alpaca Markets, Python, APIs)\n"
                    "2. Data is free (yfinance, market feeds, historical data)\n"
                    "3. Discipline is free (journaling, studying patterns, iterating)\n"
                    "4. Momentum works if you respect volatility\n\n"
                    "What stopped me before wasn't lack of money. It was lack of belief that "
                    "I could do it.\n\n"
                    "Your first goal isn't $1 million. It's $1,000 that YOU generated. "
                    "That changes everything.\n\n"
                    "Welcome to the Digital Freedom Quest. I'm not special. Neither are you. "
                    "The difference will be whether you start.'\n\n"
                    "And they pressed send.\n\n"
                    "🚀 **THE END... OR IS IT JUST THE BEGINNING?**"
                )
            }
        }

        # Randomly select chapters based on total_chapters
        selected_indices = random.sample(range(len(base_chapters)), self.total_chapters)
        selected_indices.sort()

        for idx, original_idx in enumerate(selected_indices):
            chapter = base_chapters[original_idx].copy()
            chapter["number"] = idx + 1
            self.chapters[idx] = chapter

    def get_story_intro(self) -> str:
        """Override intro for more dramatic Digital Freedom Quest intro."""
        return f"""
🚀 **{self.title}**

{self.description}

📖 **This Version:** {self.total_chapters} Chapters
👥 **For:** {self.target_audience}

Your story begins with one choice. Will you take control of your financial future?

⚡ *Type /read_chapter to start the journey of Alex...*
"""
